spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate_statistics: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdCYXNlNjRTZWNyZXRLZXlGb3JKV1RIUzI1Ng==
    expiration: 86400000

logging:
  level:
    root: INFO
    com.aghayev.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
