spring:
  application:
    name: ecommerce
  profiles:
    active: dev

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
    com.aghayev.ecommerce: INFO
